package:
  name: scared
  version: {{ environ.get("GIT_DESCRIBE_TAG", "0.9.2") }}

source:
  path: ../../

build:
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}

requirements:
  host:
    - python {{ python }}
    - setuptools>=40.0
    - wheel
    - pip
    - numpy
  run:
    - python
    - numpy
    - estraces
    - psutil
    - numba
    - scipy
about:
  home: https://gitlab.com/eshard/scared
  license: GNU LGPL V3
  license_file: LICENSE
  summary: scared is a side-channel analysis framework.
